# Generated by Django 6.0.6 on 2026-08-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_tech_stack_project_tech_stacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
