# Generated by Django 6.0.6 on 2026-10-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_for_sale',
            field=models.BooleanField(default=False, help_text='با فعال کردن این گزینه، پروژه به عنوان پروژه فروشی نمایش داده می\u200cشود.', verbose_name='پروژه فروشی است'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_sale_button_active',
            field=models.BooleanField(blank=True, help_text='اگر غیرفعال باشد، دکمه خرید نمایش داده می\u200cشود اما قابل کلیک نیست. (وقتی پروژه فروشی است، تعیین این گزینه اجباری است.)', null=True, verbose_name='دکمه خرید فعال باشد'),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, help_text='قیمت پروژه (به تومان). اگر «پروژه فروشی است» فعال باشد، پر کردن این فیلد اجباری است.', null=True, verbose_name='قیمت'),
        ),
    ]
